name: deploy_backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: GetResumeCounter
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI' 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        
        python -m pip install --upgrade pip
        pip install -r backend/api/requirements.txt --target="./backend/api/.python_packages"
        

    - name: 'Run Unit Test'
      shell: bash
      run: |
        export PYTHONPATH="${PYTHONPATH}:./api"
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pytest tests/test_counter.py
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api'
        scm-do-build-during-deployment: true
        enable-oryx-build: true
